module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      boxShadow: {
        none: "none",
        1: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        2: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        3: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 24px 24px -12px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        4: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 6px 6px -3px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 32px 32px -16px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        5: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 6px 6px -3px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 32px 32px -16px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 56px 56px -28px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        6: "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 6px 6px -3px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 12px 12px -6px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 32px 32px -16px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 64px 64px -32px var(--elevation-shadow, rgba(0, 0, 0, 0.04))",
        "primary-button":
          "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 3px -1.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 3px 4px -3px var(--color-white-56, rgba(255, 255, 255, 0.56)) inset, 0px 0px 8px -2px var(--color-white-48, rgba(255, 255, 255, 0.48)) inset",
        "secondary-button":
          "0px 1px 1px -0.5px var(--elevation-shadow, rgba(0, 0, 0, 0.04)), 0px 1px 3px -2px var(--color-white-4, rgba(255, 255, 255, 0.04)) inset, 0px -1px 3px -2px var(--neutral_inverse_white-alpha_7, rgba(0, 0, 0, 0.07)) inset",
        focus:
          "0px 0px 0px 3px var(--outline-primary_alpha, rgba(123, 92, 250, 0.24))",
        "focus-danger":
          " 0px 0px 0px 3px var(--outline-danger_alpha, rgba(240, 61, 61, 0.24))",
        "focus-success":
          "0px 0px 0px 3px var(--outline-success_alpha, rgba(53, 194, 32, 0.24))",
        "focus-gray":
          "0px 0px 0px 3px var(--outline-med_em, rgba(255, 255, 255, 0.12))",
        "focus-primary": "0px 0px 0px 3px var(--outline-primary_alpha)",
      },
    },
    fontSize: {
      "2xs": ["10px", "16px"],
      xs: ["11px", "16px"],
      sm: ["12px", "16px"],
      base: ["14px", "24px"],
      md: ["16px", "24px"],
      lg: ["18px", "28px"],
      xl: ["20px", "32px"],
      "2xl": ["26px", "40px"],
      "3xl": ["32px", "40px"],
    },
    borderRadius: {
      0: "0px",
      4: "4px",
      6: "6px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      32: "32px",
      48: "48px",
      64: "64px",
      100: "100px",
    },
    border: {
      "primary-special":
        "1px solid var(--primary_special_outline, rgba(0, 0, 0, 0.12))",
    },
    colors: {
      surface: {
        white: "var(--color-white-100)",
        black: "var(--color-black-100)",
        inverse_white_neutral: "var(--surface-inverse_white_neutral)",
        inverse_black_neutral: "var(--surface-inverse_white_black)",
        surface: {
          0: "var(--surface-white_smoke_0)",
          1: "var(--surface-surface_1)",
          2: "var(--surface-surface_2)",
          3: "var(--surface-surface_3)",
          4: "var(--surface-surface_4)",
          smoke: {
            gray: "var(--surface-surface_2)",
            "gray-em": "var(--surface-surface_2)",
          },
          white: {
            smoke: {
              0: "var(--surface-white_smoke_0)",
              1: "var(--surface-white_smoke_1)",
              2: "var(--surface-white_smoke_2)",
              3: "var(--surface-white_smoke_3)",
              4: "var(--surface-white_smoke_4)",
            },
          },
        },
        disabled: {
          "high-em": "var(--surface-disabled_high_em)",
          "med-em": "var(--surface-disabled_med_em)",
          "low-em": "var(--surface-disabled_low_em)",
          "base-em": "var(--surface-disabled_base_em)",
        },
        primary: {
          "high-em": "var(--surface-primary_high_em)",
          "med-em": "var(--surface-primary_med_em)",
          "low-em": "var(--surface-primary_low_em)",
          "base-em": "var(--surface-primary_base_em)",
          "low-em-alpha": "var(--surface-primary_low_em_alpha)",
          "base-em-alpha": "var(--surface-primary_base_em_alpha)",
        },
        secondary: {
          "high-em": "var(--surface-secondary_high_em)",
          "med-em": "var(--surface-secondary_med_em)",
          "low-em": "var(--surface-secondary_low_em)",
          "base-em": "var(--surface-secondary_base_em)",
          "low-em-alpha": "var(--surface-secondary_low_em_alpha)",
          "base-em-alpha": "var(--surface-secondary_base_em_alpha)",
        },
        success: {
          "high-em": "var(--surface-success_high_em)",
          "med-em": "var(--surface-success_med_em)",
          "low-em": "var(--surface-success_low_em)",
          "base-em": "var(--surface-success_base_em)",
          "low-em-alpha": "var(--surface-success_low_em_alpha)",
          "base-em-alpha": "var(--surface-success_base_em_alpha)",
          "low-em-alpha-2": "var(--surface-success_low_em_alpha-2)",
        },
        info: {
          "high-em": "var(--surface-info_high_em)",
          "med-em": "var(--surface-info_med_em)",
          "low-em": "var(--surface-info_low_em)",
          "base-em": "var(--surface-info_base_em)",
          "low-em-alpha": "var(--surface-info_low_em_alpha)",
          "base-em-alpha": "var(--surface-info_base_em_alpha)",
        },
        warning: {
          "high-em": "var(--surface-warning_high_em)",
          "med-em": "var(--surface-warning_med_em)",
          "low-em": "var(--surface-warning_low_em)",
          "base-em": "var(--surface-warning_base_em)",
          "low-em-alpha": "var(--surface-warning_low_em_alpha)",
          "base-em-alpha": "var(--surface-warning_base_em_alpha)",
        },
        danger: {
          "high-em": "var(--surface-danger_high_em)",
          "med-em": "var(--surface-danger_med_em)",
          "low-em": "var(--surface-danger_low_em)",
          "base-em": "var(--surface-danger_base_em)",
          "low-em-alpha": "var(--surface-danger_low_em_alpha)",
          "base-em-alpha": "var(--surface-danger_base_em_alpha)",
        },
      },
      // todo: check text variables if follow same pattern above
      text: {
        none: "var(--transparent_white)",
        "base-em": "var(--text-base_em)",
        "low-em": "var(--text-low_em)",
        "med-em": "var(--text-med_em)",
        "high-em": "var(--text-high)",
        white: "var(--color-white-100)",
        black: "var(--color-black-100)",
        "inverse-white-neutral": "var(--text-inverse_white_neutral)",
        "inverse-black-neutral": "var(--text-inverse_black_neutral)",
        primary: {
          "high-em": "var(--text-primary_high_em)",
          "med-em": "var(--text-primary_med_em)",
          "low-em": "var(--text-primary_low_em)",
          "base-em": "var(--text-primary_base_em)",
        },
        secondary: {
          "high-em": "var(--text-secondary_high_em)",
          "med-em": "var(--text-secondary_med_em)",
          "low-em": "var(--text-secondary_low_em)",
          "base-em": "var(--text-secondary_base_em)",
        },
        success: {
          "high-em": "var(--text-success_high_em)",
          "med-em": "var(--text-success_med_em)",
          "low-em": "var(--text-success_low_em)",
          "base-em": "var(--text-success_base_em)",
        },
        info: {
          "high-em": "var(--text-info_high_em)",
          "med-em": "var(--text-info_med_em)",
          "low-em": "var(--text-info_low_em)",
          "base-em": "var(--text-info_base_em)",
        },
        warning: {
          "high-em": "var(--text-warning_high_em)",
          "med-em": "var(--text-warning_med_em)",
          "low-em": "var(--text-warning_low_em)",
          "base-em": "var(--text-warning_base_em)",
        },
        danger: {
          "high-em": "var(--text-danger_high_em)",
          "med-em": "var(--text-danger_med_em)",
          "low-em": "var(--text-danger_low_em)",
          "base-em": "var(--text-danger_base_em)",
        },
      },
      outline: {
        white: "var(--outline-white)",
        black: "var(--outline-black)",
        "high-em": "var(--outline-high_em)",
        "med-em": "var(--outline-med_em)",
        "low-em": "var(--outline-low_em)",
        "base-em": "var(--outline-base_em)",
        "inverse-white-neutral": "var(--outline-inverse_white_neutral)",
        "inverse-black-neutral": "var(--outline-inverse_black_neutral)",
        primary: {
          "high-em": "var(--outline-primary-high-em)",
          "med-em": "var(--outline-primary-med-em)",
          "low-em": "var(--outline-primary-low-em)",
          "base-em": "var(--outline-primary-base-em)",
          alpha: "var(--outline-primary_alpha)",
          special: {
            top: "var(--outline-primary_special_top)",
            bottom: "var(--outline-primary_special_bottom)",
          },
        },
        secondary: {
          "high-em": "var(--outline-secondary-high-em)",
          "med-em": "var(--outline-secondary-med-em)",
          "low-em": "var(--outline-secondary-low-em)",
          "base-em": "var(--outline-secondary-base-em)",
          alpha: "var(--outline-secondary_alpha)",
          special: {
            top: "var(--outline-secondary_special_top)",
            bottom: "var(--outline-secondary_special_bottom)",
          },
        },
        success: {
          "high-em": "var(--outline-success-high-em)",
          "med-em": "var(--outline-success-med-em)",
          "low-em": "var(--outline-success-low-em)",
          "base-em": "var(--outline-success-base-em)",
          alpha: "var(--outline-success_alpha)",
        },
        info: {
          "high-em": "var(--outline-info-high-em)",
          "med-em": "var(--outline-info-med-em)",
          "low-em": "var(--outline-info-low-em)",
          "base-em": "var(--outline-info-base-em)",
          alpha: "var(--outline-info_alpha)",
        },

        warning: {
          "high-em": "var(--outline-warning-high-em)",
          "med-em": "var(--outline-warning-med-em)",
          "low-em": "var(--outline-warning-low-em)",
          "base-em": "var(--outline-warning-base-em)",
          alpha: "var(--outline-warning_alpha)",
        },

        danger: {
          "high-em": "var(--outline-danger-high-em)",
          "med-em": "var(--outline-danger-med-em)",
          "low-em": "var(--outline-danger-low-em)",
          "base-em": "var(--outline-danger-base-em)",
          alpha: "var(--outline-danger_alpha)",
        },
      },
      neutral: {
        inverse: {
          black: {
            alpha: {
              4: "var(--neutral_inverse_black-alpha_4)",
              7: "var(--neutral_inverse_black-alpha_7)",
              12: "var(--neutral_inverse_black-alpha_12)",
              16: "var(--neutral_inverse_black-alpha_16)",
              24: "var(--neutral_inverse_black-alpha_24)",
              32: "var(--neutral_inverse_black-alpha_32)",
              48: "var(--neutral_inverse_black-alpha_48)",
              56: "var(--neutral_inverse_black-alpha_56)",
              64: "var(--neutral_inverse_black-alpha_64)",
              76: "var(--neutral_inverse_black-alpha_72)",
              88: "var(--neutral_inverse_black-alpha_88)",
            },
          },
          white: {
            alpha: {
              4: "var(--neutral_inverse_white-alpha_4)",
              7: "var(--neutral_inverse_white-alpha_7)",
              12: "var(--neutral_inverse_white-alpha_12)",
              16: "var(--neutral_inverse_white-alpha_16)",
              24: "var(--neutral_inverse_white-alpha_24)",
              32: "var(--neutral_inverse_white-alpha_32)",
              48: "var(--neutral_inverse_white-alpha_48)",
              56: "var(--neutral_inverse_white-alpha_56)",
              64: "var(--neutral_inverse_white-alpha_64)",
              76: "var(--neutral_inverse_white-alpha_72)",
              88: "var(--neutral_inverse_white-alpha_88)",
            },
          },
        },
      },
      overlay: {
        high_em: "var(--color-black-48)",
        "med-em": "var(--color-black-24)",
      },
      "elevation-shadow": "var(--color-black-4)",
      transparent_inverse: "var(--transparent_white)",
    },
  },
  plugins: [],
};
